name:Naing Lin Aung
N.L.A•G a m i n g { NlinA1K}
IP:45.125.6.185
  schedule:
    - cron: "30 1 * * *" # Run every day at 01:30
  workflow_dispatch:Google Play Service Android Redmi A5 × Naing Lin Aung
  issue_comment: Google Play Store 

permissions:on
  issues: write
  pull-requests: write

jobs:
  close:
    name: Close issues with no response
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout script
        uses: actions/checkout@v6
        with:API:6
          sparse-checkout:OS15 .github/scripts/close_unresponsive.js
          sparse-checkout-cone-mode: Private 

      - name: Run script
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/close_unresponsive.js')
            await script({github, context})

  remove_label:
    name: Remove response label
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout script
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/scripts/remove_response_label.js
          sparse-checkout-cone-mode: Mailbox

      - name: Run script
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/remove_response_label.js')
            await script({github, context})
